CREATE TABLE supplier(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE categories(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE brands(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);
